# Generated by Django 4.0.1 on 2022-02-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=25)),
                ('EventName', models.CharField(max_length=25)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Location', models.CharField(max_length=25)),
                ('Leisure', models.BooleanField()),
                ('StressLevel', models.IntegerField()),
                ('Notes', models.CharField(max_length=100)),
            ],
        ),
    ]
