# Generated by Django 4.0.1 on 2022-02-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='StressLevel',
            field=models.CharField(max_length=1),
        ),
    ]
