# Generated by Django 4.0.1 on 2022-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_alter_events_stresslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='StressLevel',
            field=models.IntegerField(),
        ),
    ]
