# Generated by Django 4.0.1 on 2022-02-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_events_stresslevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindfulnessEvents',
            fields=[
                ('MindfulnessEventID', models.AutoField(primary_key=True, serialize=False)),
                ('MindfulnessEventName', models.CharField(max_length=50)),
                ('MindfulnessEventDuration', models.IntegerField()),
                ('MindfulnessEventNotes', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='Leisure',
        ),
        migrations.AddField(
            model_name='events',
            name='EventType',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
