# Generated by Django 4.0.1 on 2022-03-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0006_stresssurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='EventName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='Location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='Notes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='UserEmail',
            field=models.CharField(max_length=50),
        ),
    ]
