# Generated by Django 4.0.1 on 2022-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0008_alter_events_eventname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaks',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=100)),
                ('StreakCount', models.IntegerField()),
                ('LastLogin', models.DateTimeField()),
            ],
        ),
    ]
