# Generated by Django 4.0.1 on 2022-04-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0009_streaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaks',
            name='LifetimeScheduledMindful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streaks',
            name='UserEmail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
