# Generated by Django 4.0.1 on 2022-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.CharField(max_length=25)),
                ('EventName', models.CharField(max_length=50)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Description', models.CharField(max_length=100)),
                ('Lesiure', models.BooleanField()),
            ],
        ),
    ]
