from importlib.metadata import requires
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from django.http.response import JsonResponse

from eventApp.models import Events
from eventApp.serializers import EventsSerializer

from eventApp.models import UserPreferences
from eventApp.serializers import UserPreferencesSerializer

# Create your views here.
# At the moment this code will return all events, i will work on it later in order to make it return objects based on the UserID
@csrf_exempt
def eventsAPI(request,useremail=""):
    #Get all records that pertain to the useremail that is passed in the URL
    #Example: https://tightropeapi.herokuapp.com/events/test@test.com
    if request.method=='GET':
        #This is the same as:nevents = Events.objects.all().filter(UserEmail=useremail)
        events = Events.objects.filter(UserEmail=useremail)
        events_serializer = EventsSerializer(events, many=True)
        return JsonResponse(events_serializer.data,safe=False)

    #Add a record, must include all data EXCEPT for the the EventID, which is auto generated by the model
    #Example: https://tightropeapi.herokuapp.com/events/
    elif request.method=='POST':
        events_data = JSONParser().parse(request)
        events_serializer = EventsSerializer(data=events_data)
        events_serializer.is_valid()
        print(events_serializer.errors)
        if events_serializer.is_valid():
            events_serializer.save()
            return JsonResponse("Added event!", safe=False)
        return JsonResponse("Failed to add event.", safe=False)

    #Update a record by passing a full JSON request, that includes all information for the event INCLUDING the EventID within the request
    #Example: https://tightropeapi.herokuapp.com/events/
    elif request.method=='PUT':
        events_data = JSONParser().parse(request)
        events=Events.objects.get(EventID=events_data['EventID'])
        events_serializer = EventsSerializer(events,data=events_data)
        if events_serializer.is_valid():
            events_serializer.save()
            return JsonResponse("Updated event!",safe=False)
        return JsonResponse("Failed to update event.", safe=False)
    
    #Find and delete a record by passing a full JSON request, that includes all information for the event INCLUDING the EventID within the request
    #Example: https://tightropeapi.herokuapp.com/events/
    elif request.method=='DELETE':
        events=Events.objects.get(EventID=useremail)
        events.delete()
        return JsonResponse("Deleted Sucessfully!",safe=False)
    


@csrf_exempt
def mindfulnesseventsAPI(request):
    #Get the record that pertains to the minfulness event name
    #Example: 
    if request.method=='GET':
        pass

    #Add a record, must include all data EXCEPT for the the MindfulnessEventID, which is auto generated by the model
    #Example: 
    elif request.method=='POST':
        user_preferences = JSONParser().parse(request)
        serialized_preferences = EventsSerializer(data=user_preferences)
        serialized_preferences.is_valid()
        print(serialized_preferences.errors)
        if serialized_preferences.is_valid():
            serialized_preferences.save()
            return JsonResponse("Added Preference!", safe=False)
        return JsonResponse("Failed to add event.", safe=False)

    #Update a record by passing a full JSON request, that includes all information for the event INCLUDING the MindfulnessEventID within the request
    #Example: 
    elif request.method=='PUT':
        pass
    
    #Find and delete a record by passing a full JSON request, that includes all information for the event INCLUDING the MindfulnessEventID within the request
    #Example: 
    elif request.method=='DELETE':
        pass


@csrf_exempt
def userMindfulnessPreferences(request, useremail=""):
    #Get a given user's mindfulness preferences
    if request.method=='GET':
        userpreferences = UserPreferences.objects.filter(UserEmail=useremail)
        serialized_preferences = UserPreferencesSerializer(userpreferences, many=True)
        return JsonResponse(serialized_preferences.data,safe=False)

    #Takes a single request for a user's preferences and adds it to database
    if request.method=='POST':
        user_preferences = JSONParser().parse(request)
        serialized_preferences = UserPreferencesSerializer(data=user_preferences)
        serialized_preferences.is_valid()
        print(serialized_preferences.errors)
        if serialized_preferences.is_valid():
            serialized_preferences.save()
            return JsonResponse("Added Preference!", safe=False)
        return JsonResponse("Failed to add event.", safe=False)

    #I don't think this is relevant, this could be used to update a record of the user's preferences, but its standard
    if request.method=='PUT':
        pass

    #Deletes a record of a user's preferences
    #To me, this looks like it wouldn't work, might have to reqork this later
    if request.method=='DELETE':
        target_request=UserPreferences.objects.get(EventID=useremail)
        target_request.delete()
        return JsonResponse("Deleted Sucessfully!",safe=False)
